pool:
 vmImage: 'ubuntu-latest'
stages:
    - stage: QA
      jobs: 
        - job: QAJob

    - stage: Prod
      jobs:
        - job: ProdJob

    - stage: Test
      dependsOn: QA
      jobs:
        - job: TestJob